version: '3.1'

services:
  db:
    image: postgres
    container_name: yr-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your-review-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - yr-db-volume:/var/lib/postgresql/data

volumes:
  yr-db-volume: